from .upload_strategy import UploadStrategy
from .asset_depart import AssetDepartUploadStrategy
from .avalon_source import AvalonResourceUploader
from .taiwan_culture import TaiwanCultureUploadStrategy
from .normal_resource import NormalResourceUploadStrategy
# from .download_variant1 import DownloadVariant1UploadStrategy