from .base_folder import BaseFolder
from .folder_typing import FolderType
from .asset_depart import AssetDepartModelFolder, is_asset_depart_model_folder
from .taiwan_culture import TaiwanCultureResourceModelFolder, is_taiwan_culture_model_folder
from .avalon_source import AvalonResourceModelFolder, is_avalon_source_model_folder
from .normal_resource import NormalResourceModelFolder, is_normal_resource_model_folder
from .download_variant1 import DownloadVariant1ResourceModelFolder, is_download_variant1_model_folder
from .threedmax import ThreedMaxResourceModelFolder, is_3dmax_model_folder