from .folder_typing import AssetFolderType, FolderType
from ._taiwan_culture import TaiwanCultureResourceModelFolder, is_taiwan_culture_model_folder
from ._avalon_source import AvalonResourceModelFolder, is_avalon_source_model_folder
from ._normal_source import NormalResourceModelFolder, is_normal_resource_model_folder
from ._download_variant1 import DownloadVariant1ResourceModelFolder, is_download_variant1_model_folder
from ._3dmax import ThreedMaxResourceModelFolder, is_3dmax_model_folder